// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm23LPbXh_3hMJD1F8hKjaC4DkhL7O0-0',
    appId: '1:828221342180:web:719f8225a3c09b223587f1',
    messagingSenderId: '828221342180',
    projectId: 'i-doc-app-d3638',
    authDomain: 'i-doc-app-d3638.firebaseapp.com',
    storageBucket: 'i-doc-app-d3638.appspot.com',
    measurementId: 'G-05NMLFJT70',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKpk0-DZnH-oWLMhsrSTDYEFOD9gCvLAo',
    appId: '1:828221342180:android:9abe6ff0b11f8f3f3587f1',
    messagingSenderId: '828221342180',
    projectId: 'i-doc-app-d3638',
    storageBucket: 'i-doc-app-d3638.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8hLaMlfTGqFxNvYpMR6_-TPzsDNlmm_U',
    appId: '1:828221342180:ios:5c1ff7072e874c413587f1',
    messagingSenderId: '828221342180',
    projectId: 'i-doc-app-d3638',
    storageBucket: 'i-doc-app-d3638.appspot.com',
    iosClientId: '828221342180-g8h10c7aprf5ftot3sbpcr3k0dor2j8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.iDocApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8hLaMlfTGqFxNvYpMR6_-TPzsDNlmm_U',
    appId: '1:828221342180:ios:5c1ff7072e874c413587f1',
    messagingSenderId: '828221342180',
    projectId: 'i-doc-app-d3638',
    storageBucket: 'i-doc-app-d3638.appspot.com',
    iosClientId: '828221342180-g8h10c7aprf5ftot3sbpcr3k0dor2j8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.iDocApp',
  );
}
